# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170415_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ImageField(default=0, upload_to=b''),
        ),
    ]
