# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Training'), ('2', 'Mindset'), ('3', 'Nutrition'), ('4', 'General')], default=4, max_length=1),
        ),
    ]
