# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=300)),
                ('amount', models.FloatField(default=0, max_length=10)),
                ('meal', models.CharField(default='snack', max_length=9)),
                ('energy_kJ', models.FloatField(default=0, max_length=10)),
                ('energy_kcal', models.FloatField(default=0, max_length=10)),
                ('protein', models.FloatField(default=0, max_length=10)),
                ('carbs', models.FloatField(default=0, max_length=10)),
                ('fat', models.FloatField(default=0, max_length=10)),
                ('sugar', models.FloatField(default=0, max_length=10)),
                ('fiber', models.FloatField(default=0, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
