# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 5, 8, 9, 11, 27, 181037, tzinfo=utc))),
                ('name', models.CharField(max_length=300)),
                ('energy_kJ', models.FloatField(default=0, max_length=10)),
                ('energy_kcal', models.FloatField(default=0, max_length=10)),
                ('protein', models.FloatField(default=0, max_length=10)),
                ('carbs', models.FloatField(default=0, max_length=10)),
                ('fat', models.FloatField(default=0, max_length=10)),
                ('sugar', models.FloatField(default=0, max_length=10)),
                ('fiber', models.FloatField(default=0, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
