# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
