# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20170508_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='amount',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
