# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_nutrients_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='meal',
            field=models.CharField(default='snack', max_length=9),
        ),
    ]
